# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0b399ae939de079b86d0b3ce49a677888799faf8575847a6f1f15bda1e3889bfe466c30490c670223931067d897fab271a07d3a4f5fa241d30aa9c4c9d1bce04

test:
  secret_key_base: 2288464ab422f8d25d2b7d9e12e28fbeab1364d06269a4b1b7f3a8b42e7b989086bd19f24daa4f1472fabfb691a953a066572d643b260e57b0a88fd0ccdb3419

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
